	ORG	00H		; PROGRAM STORE LOCATION
	MOV	P0,#00H		; REFRESHING PORT-0
	MOV	P1,#00H		; REFRESHING PORT-1
	MOV	P2,#00H		; REFRESHING PORT-2
	MOV	P3,#00H		; REFRESHING PORT-3

AGAIN:	
	SETB	P2.0		; PORT-2 PIN-0 HIGH
	LCALL   DELAY		; CALL DELAY 
	CLR	P2.0		; PORT-2 PIN-0 LOW
	LCALL   DELAY		; CALL DELAY 

	SETB	P2.1		; PORT-2 PIN-0 HIGH
	LCALL   DELAY		; CALL DELAY 
	CLR	P2.1		; PORT-2 PIN-0 LOW
	LCALL   DELAY		; CALL DELAY 

	SETB	P2.2		; PORT-2 PIN-0 HIGH
	LCALL   DELAY		; CALL DELAY 
	CLR	P2.2		; PORT-2 PIN-0 LOW
	LCALL   DELAY		; CALL DELAY 

	SETB	P2.3		; PORT-2 PIN-0 HIGH
	LCALL   DELAY		; CALL DELAY 
	CLR	P2.3		; PORT-2 PIN-0 LOW
	LCALL   DELAY		; CALL DELAY 

	SETB	P2.4		; PORT-2 PIN-0 HIGH
	LCALL   DELAY		; CALL DELAY 
	CLR	P2.4		; PORT-2 PIN-0 LOW
	LCALL   DELAY		; CALL DELAY 

	SETB	P2.5		; PORT-2 PIN-0 HIGH
	LCALL   DELAY		; CALL DELAY 
	CLR	P2.5		; PORT-2 PIN-0 LOW
	LCALL   DELAY		; CALL DELAY 

	SETB	P2.6		; PORT-2 PIN-0 HIGH
	LCALL   DELAY		; CALL DELAY 
	CLR	P2.6		; PORT-2 PIN-0 LOW
	LCALL   DELAY		; CALL DELAY 

	SETB	P2.7		; PORT-2 PIN-0 HIGH
	LCALL   DELAY		; CALL DELAY
	CLR	P2.7		; PORT-2 PIN-0 LOW
	LCALL   DELAY		; CALL DELAY

	MOV	P2, #11111111B
	LCALL   DELAY		; CALL DELAY 
	MOV	P2, #00000000B
	LCALL   DELAY		; CALL DELAY 

	LJMP	AGAIN		; LOOP FOREVER TO LABEL AGAIN


DELAY:				; DELAY SUBROUTINE 
	MOV	R7,#20		;		
L3 :	MOV	R6,#100		;
L2 :	MOV	R5,#100		;
L1 :	DJNZ	R5,L1		;
	DJNZ	R6,L2		;
	DJNZ	R7,L3		;
	RET			; END DELAY SUBROUTINE

	END			; END OF PROGRAM